FROM node:alpine as build

WORKDIR /indecision-app
 
COPY . ./

RUN yarn

RUN yarn build

# production environment
FROM nginx:stable-alpine

COPY --from=build /indecision-app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]