version: '3.7'

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: saarthak08/indecision-app-dev
    volumes:
      - '.:/indecision-app'
      - '/indecision-app/node_modules'
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true